from fpdf import FPDF
from datetime import datetime
import random
import io

def generate_ref_id():
    return f"VNS-{datetime.now().strftime('%Y%m%d')}-{random.randint(1000, 9999)}"

def generate_pdf(fullname, complaint_text, department, dept_description):

    dept_description = dept_description.replace("\u2014", "-").replace("\u2013", "-")

    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(25, 20, 25)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_font("DejaVu", "", "DejaVuSans.ttf")
    pdf.add_font("DejaVu", "B", "DejaVuSans.ttf")

    today = datetime.now().strftime("%d %B %Y")
    ref_id = generate_ref_id()

    #HEADER 

    pdf.set_font("DejaVu", "B", 16)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "VaniSeva", ln=True, align="C")

    pdf.set_font("DejaVu", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, "Citizen Complaint Department Identifier", ln=True, align="C")

    pdf.ln(4)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(25, pdf.get_y(), 185, pdf.get_y())
    pdf.ln(8)

    #DATE & REF

    pdf.set_font("DejaVu", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, f"Date: {today}", ln=True)
    pdf.cell(0, 6, f"Reference ID: {ref_id}", ln=True)
    pdf.ln(6)

    #TO ADDRESS

    pdf.set_font("DejaVu", "B", 10)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 6, "To,", ln=True)
    pdf.set_font("DejaVu", "", 10)
    pdf.cell(0, 6, f"The Head of Department,", ln=True)
    pdf.cell(0, 6, f"{department}", ln=True)
    pdf.cell(0, 6, "Andhra Pradesh, India", ln=True)
    pdf.ln(6)

    #SUBJECT

    pdf.set_font("DejaVu", "B", 10)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 6, f"Subject: Complaint Regarding - {dept_description}", ln=True)
    pdf.ln(6)

    pdf.set_draw_color(200, 200, 200)
    pdf.line(25, pdf.get_y(), 185, pdf.get_y())
    pdf.ln(6)
    pdf.set_font("DejaVu", "", 10)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 6, "Respected Sir / Madam,", ln=True)
    pdf.ln(4)

    #BODY

    pdf.set_font("DejaVu", "", 10)
    intro = (
        f"I, {fullname}, a citizen of Andhra Pradesh, wish to bring the following "
        f"complaint to your kind attention. I request your department to take "
        f"appropriate action at the earliest."
    )
    pdf.multi_cell(0, 7, intro)
    pdf.ln(4)

    pdf.set_font("DejaVu", "B", 10)
    pdf.cell(0, 6, "Complaint Details:", ln=True)
    pdf.set_font("DejaVu", "", 10)

    # handle non-latin characters safely by encoding
    safe_complaint = complaint_text.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 7, safe_complaint)
    pdf.ln(4)

    pdf.set_font("DejaVu", "", 10)
    closing = (
        "I kindly request you to acknowledge receipt of this complaint and "
        "take necessary action as per the applicable government procedures. "
        "I look forward to a prompt resolution."
    )
    pdf.multi_cell(0, 7, closing)
    pdf.ln(8)

    #SIGNATURE

    pdf.set_font("DejaVu", "", 10)
    pdf.cell(0, 6, "Yours sincerely,", ln=True)
    pdf.ln(10)
    pdf.set_font("DejaVu", "B", 10)
    pdf.cell(0, 6, fullname, ln=True)
    pdf.set_font("DejaVu", "", 10)
    pdf.cell(0, 6, f"Date: {today}", ln=True)
    pdf.ln(8)

    #FOOTER

    pdf.set_draw_color(200, 200, 200)
    pdf.line(25, pdf.get_y(), 185, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("DejaVu", "", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, f"Generated by VaniSeva  |  Reference: {ref_id}  |  {today}", ln=True, align="C")

    #RETURN AS BYTES

    pdf_bytes = bytes(pdf.output())
    return pdf_bytes
